apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    {{- if .Values.repoURL }}
    repoURL: {{ .Values.repoURL }} # "https://airflow.apache.org/"
    path: infra/airflow
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
    {{- else }}
    repoURL: https://github.com/FerozLabs/promptly-data-pipelines.git
    path: infra/airflow
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
    {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: airflow
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true